In [24]:
from tensorflow.keras.preprocessing.text import one_hot

In [25]:
# sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [26]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [27]:
# Define the vocabulary size
voc_size=10000

In [28]:
# One Hot Representation
one_hot_repr=[one_hot(words, voc_size)for words in sent]
one_hot_repr

[[6278, 6308, 5956, 6726],
 [6278, 6308, 5956, 9668],
 [6278, 5920, 5956, 8361],
 [7793, 167, 7089, 4023, 163],
 [5240, 6278, 1604, 5956, 9245],
 [7469, 9491, 7102, 4023]]

In [29]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [30]:
import numpy as np

In [31]:
# Since rnn needs same no. of words through input use pad sequences
sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6278 6308 5956 6726]
 [   0    0    0    0 6278 6308 5956 9668]
 [   0    0    0    0 6278 5920 5956 8361]
 [   0    0    0 7793  167 7089 4023  163]
 [   0    0    0 5240 6278 1604 5956 9245]
 [   0    0    0    0 7469 9491 7102 4023]]


In [32]:
# Feature representation
dim=10


In [33]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Hp\Desktop\DL NLP\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [34]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 323ms/step


array([[[ 1.9694567e-03, -2.7096160e-03,  4.8400108e-02, -1.7129838e-02,
          4.8407380e-02, -2.2811199e-02, -1.3496947e-02,  1.0621630e-02,
          4.4853453e-02,  3.0824590e-02],
        [ 1.9694567e-03, -2.7096160e-03,  4.8400108e-02, -1.7129838e-02,
          4.8407380e-02, -2.2811199e-02, -1.3496947e-02,  1.0621630e-02,
          4.4853453e-02,  3.0824590e-02],
        [ 1.9694567e-03, -2.7096160e-03,  4.8400108e-02, -1.7129838e-02,
          4.8407380e-02, -2.2811199e-02, -1.3496947e-02,  1.0621630e-02,
          4.4853453e-02,  3.0824590e-02],
        [ 1.9694567e-03, -2.7096160e-03,  4.8400108e-02, -1.7129838e-02,
          4.8407380e-02, -2.2811199e-02, -1.3496947e-02,  1.0621630e-02,
          4.4853453e-02,  3.0824590e-02],
        [ 2.0303354e-03,  1.2009751e-02,  3.8898382e-02,  2.4547029e-02,
         -4.5489520e-05,  2.2110987e-02,  3.6752548e-02,  4.6032872e-02,
          2.7542088e-02,  9.2333779e-03],
        [-1.9802129e-02,  4.2945448e-02,  2.3361992e-02, -3.

In [36]:
embedded_docs[0]

array([   0,    0,    0,    0, 6278, 6308, 5956, 6726], dtype=int32)

In [37]:
len(embedded_docs)

6